/* eFashion 2                                               */

--CREATE SCHEMA USERxx;
create schema demo01; 
grant select on schema "DEMO01" to _SYS_REPO with grant option;


--SET SCHEMA NEO_61P14Y3L735NHL2PUTI8Q13TV;
set schema demo01;
select current_schema from dummy;
 

CREATE  COLUMN TABLE "SHOP_FACTS"(
	"SHOP_FACTS_ID" INTEGER NOT NULL,
	"ARTICLE_ID" INTEGER NOT NULL,
	"COLOR_CODE" INTEGER NOT NULL,
	"WEEK_ID" INTEGER NOT NULL,
	"SHOP_ID" INTEGER NOT NULL,
	"MARGIN" DECIMAL NOT NULL,
	"AMOUNT_SOLD" DECIMAL NOT NULL,
	"QUANTITY_SOLD" INTEGER NOT NULL,
PRIMARY KEY ("SHOP_FACTS_ID","ARTICLE_ID","WEEK_ID","SHOP_ID") );

CREATE  COLUMN TABLE "OUTLET_LOOKUP" (
	"SHOP_ID" INTEGER NOT NULL,
	"SHOP_NAME" VARCHAR(50) NULL,
	"ADDRESS_1" VARCHAR(255) NULL,
	"MANAGER" VARCHAR(255) NULL,
	"DATE_OPEN" VARCHAR(255) NULL,
	"LONG_OPENING_HOURS_FLAG" VARCHAR(1) NULL,
	"OWNED_OUTRIGHT_FLAG" VARCHAR(1) NULL,
	"FLOOR_SPACE" INTEGER NULL,
	"ZIP_CODE" INTEGER NULL,
	"CITY" VARCHAR(255) NULL,
	"STATE" VARCHAR(255) NULL,
PRIMARY KEY ("SHOP_ID") );	

CREATE  COLUMN TABLE "ARTICLE_LOOKUP"(
	"ARTICLE_ID" INTEGER NOT NULL,
	"ARTICLE_LABEL" VARCHAR(100) NULL,
	"SALE_PRICE" DECIMAL NULL,
	"CATEGORY_ID" INTEGER NOT NULL,
PRIMARY KEY ("ARTICLE_ID") );

CREATE  COLUMN TABLE "CATEGORY_LOOKUP"(
	"CATEGORY_ID" INTEGER NOT NULL,
	"CATEGORY" VARCHAR(30) NULL,
	"FAMILY_CODE" VARCHAR(3) NULL,
PRIMARY KEY ("CATEGORY_ID") );

CREATE  COLUMN TABLE "FAMILY_LOOKUP"(
	"FAMILY_CODE" VARCHAR(3) NULL,
	"FAMILY_NAME" VARCHAR(30) NULL,
PRIMARY KEY ("FAMILY_CODE") );

CREATE  COLUMN TABLE "CALENDAR_YEAR_LOOKUP" (
        "WEEK_ID" INTEGER NOT NULL,
        "WEEK_IN_YEAR" INTEGER NULL,
        "YR" VARCHAR(4) NULL,
        "FISCAL_PERIOD" VARCHAR(4) NULL,
        "YERA_WEEK" VARCHAR(7) NULL,
        "QTR" VARCHAR(1) NULL,
        "MONTH_NAME" VARCHAR(15) NULL,
        "MTH" INTEGER NULL,
        "HOLIDAY_FLAG" VARCHAR(1) NULL,
PRIMARY KEY ("WEEK_ID") );
 
CREATE COLUMN TABLE "ARTICLE_COLOR_LOOKUP"(
	"ARTICLE_COLOR_LOOKUP_ID" INTEGER NOT NULL,
	"ARTICLE_ID" INTEGER NOT NULL,
	"COLOR_CODE" INTEGER NULL,
	"ARTICLE_LABEL" VARCHAR(255) NULL,
	"COLOR_LABEL" VARCHAR(255) NULL,
	"CATEGORY" VARCHAR(255) NULL,
	"SALE_PRICE" DECIMAL NULL,
	"FAMILY_NAME" VARCHAR(30) NULL,
	"FAMILY_CODE" VARCHAR(3) NULL,
PRIMARY KEY ("ARTICLE_COLOR_LOOKUP_ID","ARTICLE_ID") ); 
