SET SCHEMA USERxx;

DROP TABLE "SHOP_FACTS";
DROP TABLE "OUTLET_LOOKUP";	
DROP TABLE "ARTICLE_LOOKUP";
DROP TABLE "CATEGORY_LOOKUP";
DROP TABLE "FAMILY_LOOKUP";
DROP TABLE "CALENDAR_YEAR_LOOKUP" ;
DROP TABLE "ARTICLE_COLOR_LOOKUP"; 
