SET SCHEMA DM_PAL;
-----------------------------------------
---Random sampling process---------------
-----------------------------------------
DROP TABLE PAL_DISTRRANDOM_DISTRPARAM_TAB;
CREATE COLUMN TABLE PAL_DISTRRANDOM_DISTRPARAM_TAB (
NAME VARCHAR(50),
VAL VARCHAR(50)
);
DROP TABLE PAL_PARAMETER_TBL;
CREATE COLUMN TABLE PAL_PARAMETER_TBL (
PARAM_NAME VARCHAR (256),
INT_VALUE INTEGER,
DOUBLE_VALUE DOUBLE,
STRING_VALUE VARCHAR (1000)
);
DROP TABLE PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
CREATE COLUMN TABLE PAL_DISTRRANDOM_RESULT_TAB_REVENUE (
ID INTEGER,
RANDOM DOUBLE
);
DROP TABLE PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CREATE COLUMN TABLE PAL_DISTRRANDOM_RESULT_TAB_COSTS (
ID INTEGER,
RANDOM DOUBLE
);
DROP TABLE PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
CREATE COLUMN TABLE PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS (
ID INTEGER,
RANDOM DOUBLE
);
DROP TABLE PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT;
CREATE COLUMN TABLE PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT (
ID INTEGER,
RANDOM DOUBLE
);
---------------------------
----------YEAR 1 -----------
-----Product revenue------
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '0');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '0.0001');
INSERT INTO PAL_PARAMETER_TBL VALUES ('NUM_RANDOM',5000,null,null);
INSERT INTO PAL_PARAMETER_TBL VALUES ('SEED', 0, null, null);
select * from PAL_DISTRRANDOM_DISTRPARAM_TAB;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_REVENUE) WITH OVERVIEW;
SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
---------Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '1000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '5625');
select * from PAL_DISTRRANDOM_DISTRPARAM_TAB;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
--------OVERHEADS---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'UNIFORM');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MIN', '1400');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MAX', '1500');
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
-------INVESTMENT---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '10000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '250000');
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT;
--------calculate cash flow -------
DROP TABLE PAL_CASHFLOW_YEAR1;
CREATE COLUMN TABLE PAL_CASHFLOW_YEAR1(
ID INTEGER,
CASH DOUBLE
);
INSERT INTO PAL_CASHFLOW_YEAR1
SELECT PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID,
PAL_DISTRRANDOM_RESULT_TAB_REVENUE.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_COSTS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT.RANDOM
FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_COSTS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_COSTS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT.ID;
SELECT * FROM PAL_CASHFLOW_YEAR1;
---------------------------------
------------YEAR 2 --------------
--product revenue----
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '3000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '90000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_REVENUE) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
----Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '1000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '5625');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
----OVERHEADS---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'UNIFORM');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MIN', '1800');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MAX', '2200');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
----INVESTMENT---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '2000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '10000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT;
--------calculate cash flow -------
DROP TABLE PAL_CASHFLOW_YEAR2;
CREATE COLUMN TABLE PAL_CASHFLOW_YEAR2(
ID INTEGER,
CASH DOUBLE
);
INSERT INTO PAL_CASHFLOW_YEAR2
SELECT PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID,
PAL_DISTRRANDOM_RESULT_TAB_REVENUE.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_COSTS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT.RANDOM
FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_COSTS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_COSTS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_INVESTMENT.ID;
--SELECT * FROM PAL_CASHFLOW_YEAR2;
-----------------------------
----------YEAR 3 ------------
----product revenue----
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '8000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '640000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_REVENUE) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
----Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '2500');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '35156.25');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
----Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '2500');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '35156.25');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
----OVERHEADS---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'UNIFORM');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MIN', '2200');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MAX', '2800');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
--------calculate cash flow -------
DROP TABLE PAL_CASHFLOW_YEAR3;
CREATE COLUMN TABLE PAL_CASHFLOW_YEAR3(
ID INTEGER,
CASH DOUBLE
);
INSERT INTO PAL_CASHFLOW_YEAR3
SELECT PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID,
PAL_DISTRRANDOM_RESULT_TAB_REVENUE.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_COSTS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.RANDOM
FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_COSTS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_COSTS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.ID;
--SELECT * FROM PAL_CASHFLOW_YEAR3;
-----------------------------
--------YEAR 4 --------------
--Product revenue---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '18000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '3240000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_REVENUE) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
----Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '7000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '275625');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
----OVERHEADS---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'UNIFORM');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MIN', '2600');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MAX', '3400');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
--------calculate cash flow -------
DROP TABLE PAL_CASHFLOW_YEAR4;
CREATE COLUMN TABLE PAL_CASHFLOW_YEAR4(
ID INTEGER,
CASH DOUBLE
);
INSERT INTO PAL_CASHFLOW_YEAR4
SELECT PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID,
PAL_DISTRRANDOM_RESULT_TAB_REVENUE.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_COSTS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.RANDOM
FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_COSTS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_COSTS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID=PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.ID;
--SELECT * FROM PAL_CASHFLOW_YEAR4;
----------------------------
-------YEAR 5 --------------
--Product revenue----
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '30000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '9000000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_REVENUE) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE;
----Product Costs---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'NORMAL');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MEAN', '10000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('VARIANCE', '562500');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_COSTS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_COSTS;
----OVERHEADS---------
DELETE FROM PAL_DISTRRANDOM_DISTRPARAM_TAB;
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('DISTRIBUTIONNAME', 'UNIFORM');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MIN', '3000');
INSERT INTO PAL_DISTRRANDOM_DISTRPARAM_TAB VALUES ('MAX', '4000');
DELETE FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
CALL "_SYS_AFL"."PAL_DISTRIBUTION_RANDOM"(PAL_DISTRRANDOM_DISTRPARAM_TAB, PAL_PARAMETER_TBL, PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS) WITH OVERVIEW;
--SELECT * FROM PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS;
--------calculate cash flow -------
DROP TABLE PAL_CASHFLOW_YEAR5;
CREATE COLUMN TABLE PAL_CASHFLOW_YEAR5(
ID INTEGER,
CASH DOUBLE
);
INSERT INTO PAL_CASHFLOW_YEAR5
SELECT PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID,
PAL_DISTRRANDOM_RESULT_TAB_REVENUE.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_COSTS.RANDOM -
PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.RANDOM
FROM PAL_DISTRRANDOM_RESULT_TAB_REVENUE
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_COSTS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_COSTS.ID
LEFT JOIN PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS ON PAL_DISTRRANDOM_RESULT_TAB_REVENUE.ID = PAL_DISTRRANDOM_RESULT_TAB_OVERHEADS.ID;
--SELECT * FROM PAL_CASHFLOW_YEAR5;

-- STEP2
-- サンプリングごとに、次の式で投資の正味現在価値を計算します。
SET SCHEMA DM_PAL;
---- calculate net present value of investment ----
DROP TABLE NPV;
CREATE COLUMN TABLE NPV (
NPVALUE DOUBLE
);
INSERT INTO NPV SELECT PAL_CASHFLOW_YEAR1.CASH +
PAL_CASHFLOW_YEAR2.CASH/1.05 +
PAL_CASHFLOW_YEAR3.CASH/POWER(1.05,2) +
PAL_CASHFLOW_YEAR4.CASH/POWER(1.05,3) +
PAL_CASHFLOW_YEAR5.CASH/POWER(1.05,4)
FROM PAL_CASHFLOW_YEAR1 LEFT JOIN PAL_CASHFLOW_YEAR2 ON PAL_CASHFLOW_YEAR1.ID = PAL_CASHFLOW_YEAR2.ID
LEFT JOIN PAL_CASHFLOW_YEAR3 ON PAL_CASHFLOW_YEAR1.ID = PAL_CASHFLOW_YEAR3.ID
LEFT JOIN PAL_CASHFLOW_YEAR4 ON PAL_CASHFLOW_YEAR1.ID = PAL_CASHFLOW_YEAR4.ID
LEFT JOIN PAL_CASHFLOW_YEAR5 ON PAL_CASHFLOW_YEAR1.ID = PAL_CASHFLOW_YEAR5.ID;
SELECT * FROM NPV;

--STEP3
-- 投資の正味現在価値の分布をプロットし、分布フィットを実行して、正規分布を投資のNPVに適合させます。 （中央極限定理は、出力分布は正規分布になると述べています。)

SET SCHEMA DM_PAL;
---------------------------------------
------- distribution fit process ---
---------------------------------------
DROP TABLE PAL_PARAMETER_TBL;
CREATE COLUMN TABLE PAL_PARAMETER_TBL (
PARAM_NAME VARCHAR (256),
INT_VALUE INTEGER,
DOUBLE_VALUE DOUBLE,
STRING_VALUE VARCHAR (1000)
);
INSERT INTO PAL_PARAMETER_TBL VALUES ('DISTRIBUTIONNAME', null, null, 'NORMAL');
INSERT INTO PAL_PARAMETER_TBL VALUES ('OPTIMAL_METHOD', 0, null, null);
DROP TABLE PAL_DISTRFIT_ESTIMATION_TBL;
CREATE COLUMN TABLE PAL_DISTRFIT_ESTIMATION_TBL (
NAME VARCHAR(50),
VAL VARCHAR(50)
);
DROP TABLE PAL_DISTRFIT_STATISTICS_TBL;
CREATE COLUMN TABLE PAL_DISTRFIT_STATISTICS_TBL (
NAME VARCHAR(50),
VAL DOUBLE
);
CALL "_SYS_AFL"."PAL_DISTRIBUTION_FIT"(NPV, PAL_PARAMETER_TBL, PAL_DISTRFIT_ESTIMATION_TBL, PAL_DISTRFIT_STATISTICS_TBL) WITH OVERVIEW;
SELECT * FROM PAL_DISTRFIT_ESTIMATION_TBL;

--STEP4
--近似モデルに従って、累積分布関数を実行して、投資のNPVが所定の投資のNPV以下である確率を取得します。

SET SCHEMA DM_PAL;
---------------------------------------
----distribution probability process --
---------------------------------------
DROP TABLE PAL_DISTRPROB_DATA_TBL;
CREATE TABLE PAL_DISTRPROB_DATA_TBL (
DATACOL DOUBLE
);
INSERT INTO PAL_DISTRPROB_DATA_TBL VALUES (7000);
INSERT INTO PAL_DISTRPROB_DATA_TBL VALUES (8000);
INSERT INTO PAL_DISTRPROB_DATA_TBL VALUES (9000);
INSERT INTO PAL_DISTRPROB_DATA_TBL VALUES (10000);
INSERT INTO PAL_DISTRPROB_DATA_TBL VALUES (11000);
DROP TABLE PAL_DISTRPROB_DISTRPARAM_TBL;
CREATE TABLE PAL_DISTRPROB_DISTRPARAM_TBL (
NAME VARCHAR(50),
VALUEE VARCHAR(50)
);
INSERT INTO PAL_DISTRPROB_DISTRPARAM_TBL VALUES ('DISTRIBUTIONNAME', 'Normal');
INSERT INTO PAL_DISTRPROB_DISTRPARAM_TBL VALUES ('MEAN', '100');
INSERT INTO PAL_DISTRPROB_DISTRPARAM_TBL VALUES ('VARIANCE', '1');
UPDATE PAL_DISTRPROB_DISTRPARAM_TBL SET VALUEE = (SELECT VAL FROM PAL_DISTRFIT_ESTIMATION_TBL WHERE NAME = 'MEAN') WHERE NAME = 'MEAN';
UPDATE PAL_DISTRPROB_DISTRPARAM_TBL SET VALUEE = (SELECT VAL*VAL FROM PAL_DISTRFIT_ESTIMATION_TBL WHERE NAME = 'SD') WHERE NAME = 'VARIANCE';
SELECT * FROM PAL_DISTRPROB_DISTRPARAM_TBL;
DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
PARAM_NAME VARCHAR (256),
INT_VALUE INTEGER,
DOUBLE_VALUE DOUBLE,
STRING_VALUE VARCHAR (1000)
);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('LOWER_UPPER',0,null,null);
CALL "_SYS_AFL"."PAL_DISTRIBUTION_FUNCTION"(PAL_DISTRPROB_DATA_TBL, PAL_DISTRPROB_DISTRPARAM_TBL, #PAL_PARAMETER_TBL, ?);
