
-- Connect to SystemDB

-- set import path for MDC
--/*
ALTER SYSTEM ALTER CONFIGURATION ('global.ini','SYSTEM')
SET ('import_export', 'csv_import_path_filter') = '/install/eFashion'
WITH RECONFIGURE;
--*/
-- Connect to user DB
-- set schema USERxx;
set schema demo01;

IMPORT FROM CSV FILE '/install/eFashion/article.csv' INTO "ARTICLE_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "ARTICLE_LOOKUP";

IMPORT FROM CSV FILE '/install/eFashion/category.csv' INTO "CATEGORY_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "CATEGORY_LOOKUP";

IMPORT FROM CSV FILE '/install/eFashion/family.csv' INTO "FAMILY_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "FAMILY_LOOKUP";

IMPORT FROM CSV FILE '/install/eFashion/shop_facts.csv' INTO "SHOP_FACTS"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "SHOP_FACTS";

IMPORT FROM CSV FILE '/install/eFashion/outlet_lookup.csv' INTO "OUTLET_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "OUTLET_LOOKUP";

IMPORT FROM CSV FILE '/install/eFashion/calendar_year_lookup.csv' INTO "CALENDAR_YEAR_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "CALENDAR_YEAR_LOOKUP";

IMPORT FROM CSV FILE '/install/eFashion/article_color_lookup.csv' INTO "ARTICLE_COLOR_LOOKUP"
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ';'
THREADS 4 BATCH 20000;
MERGE DELTA OF "ARTICLE_COLOR_LOOKUP";
